use krunal

select * from customers
select * from products
select * from orders

--1. Retrieve a list of all orders. Show the CustomerName, the ProductName, and the OrderDate
create procedure splistoforders
as
begin
    select c.customername,p.productname,o.orderdate from customers c
    join orders o
    on c.customerid=o.customerid
    join products p
    on o.productid=p.productid
end

execute splistoforders

--2. Calculate the total revenue generated by each product category. Show the Category and the TotalRevenue
create procedure spproductrevenue
@pcategory varchar(25),
@revenue int output
as
begin
    select @revenue=sum(o.quantity*p.price) from products p
    join orders o
    on p.productid=o.productid
    where category=@pcategory
end

declare @total int
execute spproductrevenue 'vehicle',@total output
print 'total is-' +cast(@total as varchar)

--3. List all customers who have never placed an order.
create procedure spgetcustomerneverorder
as
begin
    select c.customername from customers c
    left join orders o
    on c.customerid=o.customerid
    where o.customerid is null
end

execute spgetcustomerneverorder

--4. Select all customers and their order IDs. If they have no orders, the OrderID will naturally be NULL.
create procedure spcustomerwithorder
as
begin
    select c.customername,o.orderid from customers c
    full join orders o
    on c.customerid=o.customerid
end

execute spcustomerwithorder

--5. Find the names of customers who have bought more than 10 items in total.
create procedure spcustomerbought
@cname varchar(20),
@total int output
as
begin
    select @total=sum(o.quantity) from customers c
    join orders o
    on c.customerid=o.customerid
    where c.customername=@cname
    having sum(o.quantity)>10
end

declare @items int
execute spcustomerbought 'krunal',@items output
print 'item total is-'+cast(@items as varchar)

--6. Display a list of all Products and the OrderID associated with them. This list must include products that have never been sold.

--7. List all ProductNames that have been ordered by customers living in 'Vadodara’.

--8. Display a list of all Product Names and their Prices, sorted from the cheapest to the most expensive.
